version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: socialens-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: socialens
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - socialens-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: socialens-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - socialens-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialens-backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/socialens?authSource=admin
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - socialens-network

  # Celery Worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialens-celery-worker
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/socialens?authSource=admin
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
      - backend
    command: celery -A workers.tasks.celery_app worker --loglevel=info --concurrency=1
    networks:
      - socialens-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: socialens-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - socialens-network

volumes:
  mongodb_data:

networks:
  socialens-network:
    driver: bridge 